#!/bin/sh
#Rscript -e "rmarkdown::render('index.Rmd','html_document')"
Rscript -e "rmarkdown::render('index.Rmd','bookdown::gitbook')"
#Rscript -e "bookdown::render_book('index.Rmd','bookdown::gitbook')"

